export const demoUserInitialData = {
  is_employee: false,
  is_friend: false,
  is_demo: true,
  name: "DemoUser",
  total_karma: 1,
  link_karma: 1,
  id: "demoUserID",
  comment_karma: 1,
  verified: true,
  has_verified_email: true,
  created: 1669541902.0,
  created_utc: 1669541902.0,
  icon_img:
    "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_5.png",
  snoovatar_img:
    "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_5.png",
  subscribedSubreddits: [
    "AskReddit",
    "pics",
    "MadeMeSmile",
    "mildlyinteresting",
    "UpliftingNews",
  ],
  visitedPosts: [],
  upvotedSubmissions: [],
  downvotedSubmissions: [],
  savedSubmissions: [],
  hiddenSubmissions: [],
};
